- auctions/serializers.py
- auctions/tests/serializer_tests.py
- auctions/tests/view_tests.py
- auctions/views.py
- codesy/tests/serializer_tests.py
- requirements.txt
Need @jsatt to take a look at this and spot-check DRF api requests via the API site. I went thru as much as I can, so a quick spot-check of create, retrieve, update, and delete of bids should be enough.
> update DRF to 3.x

- .travis.yml
- docs/development.rst
- requirements.txt
All docs changes, so no real changes to production.
Testing the new deploy request link I added to the docs. I.e., requesting a merge from master to production should trigger a production deployment via Travis when the commits are merged.
> [deploy] Request

- auctions/migrations/0006_auto_20150103_1924.py
- auctions/models.py
This should have the proper migration #.
> fix #82 - make ask and offer optional

- auctions/templates/bid.html
- static/css/styles.css
Supersedes https://github.com/codesy/codesy/pull/109
> for codesy/chrome-extension#36 - updates on backend

- auctions/templates/bid.html
- auctions/tests/view_tests.py
- auctions/views.py
- codesy/context_processors.py
- codesy/settings.py
- codesy/templates/401.html
**DNM** until https://github.com/codesy/codesy/pull/110 is merged; then rebase this on master.
> fix #105 - custom 401 template for sign-in

- codesy/base/admin.py
- codesy/templates/base.html
- codesy/templates/home.html
- codesy/tests/view_tests.py
- codesy/views.py
- static/css/styles.css
add payments to user change form in admin
make gravatar url protocol-relative
> fix #75 - add payment feedback to home page

- codesy/templates/home.html
- static/js/app.js
These changes move the inline javascript on the home.html template to a static app.js file.  
Changes to home.html
-Hidden input elements where the inline code used django tags.
The token is already saved as a hidden input element
Added a hidden input for user id
-Added a new link to show the cc form if hidden
Changes to the inline js:
- wrapped code in a document load 
-  changed ajax PUSH to used hidden input tags
> Show cc form

- Procfile
- codesy/settings.py
to be used with the Heroku Scheduler Add-on
> for #74 - add processes for send_mail and retry_deferred

- auctions/templates/401.html
- auctions/templates/base_widget.html
- auctions/templates/bid.html
move 401.html to auctions and extend from base_widget.html
> fix #113 - new base_widget.html template

- auctions/admin.py
- auctions/migrations/0007_claim.py
- auctions/migrations/0008_auto_20150301_1953.py
- auctions/models.py
- auctions/serializers.py
- auctions/templates/base_widget.html
- auctions/templates/bid.html
- auctions/templates/confirm_claim.html
- auctions/templates/includes/claim_form.html
- auctions/tests/model_tests.py
- auctions/tests/serializer_tests.py
- auctions/tests/view_tests.py
- auctions/urls.py
- auctions/views.py
- static/css/styles.css
For https://github.com/codesy/codesy/issues/131 ...
* New `Claim` model wired with a DRF `ViewSet`
* "Confirm Claim" endpoint at `GET /claim/confirm?bid={id}` with a form to POST to the `Claim` API
* Including a link to the "Confirm Claim" form in the notification email
* Include the "Confirm Claim" form in the widget
> for #131 - claim issues for payout

- auctions/templates/bid.html
- auctions/templates/includes/claim_form.html
- auctions/tests/view_tests.py
- auctions/views.py
set Bid's Issue when creating Bid
> fix #142, fix #146 - show pending claims in widget

- auctions/templates/base_widget.html
- auctions/templates/bid.html
- auctions/templates/includes/claim_form.html
- static/css/styles.css
-reformatted to stacked form
-cleaned up new bid claim
> Restyle widget

- codesy/templates/base.html
- codesy/templates/home.html
Because [DareBoost](https://www.dareboost.com/en/report/1522/5524c68be4b02866159dc1de) and [Matt Cutts](https://support.google.com/webmasters/answer/79812?hl=en) told me to.
> add meta-description tag

- .gitignore
- app.json
- auctions/tests/utils_tests.py
- auctions/utils.py
If an issue has disappeared since first added to codesy, dont halt
the entire update_bid_issues batch on its UnkownObjectException.
TODO: log the exception somewhere
> fix #158 - pass UnknownObjectException in issue_state

- codesy/base/admin.py
- codesy/base/migrations/0002_auto_20151204_1812.py
- codesy/base/models.py
- codesy/serializers.py
- codesy/templates/home.html
- codesy/tests/serializer_tests.py
- static/js/app.js
Change from balanced to [Stripe.js](https://stripe.com/docs/tutorials/forms) for storing card tokens.
> #159 - use Stripe for cards

- api/templates/claim_status.html
- api/templates/includes/vote_form.html
- api/views.py
This fixes #232 but we need to file a claim to come back and make these pretty.
> Voting for 232

- .gitignore
- .travis.yml
- requirements-test.txt
- tox.ini
tidy up some travis and tox directives
> fix #243: add TEST_RUNNER to tox.ini passenv

- auctions/models.py
- auctions/templates/addon/includes/claim_form.html
- auctions/templates/addon/widget.html
- auctions/templates/bid_list.html
- auctions/templatetags/auctions_extras.py
- auctions/tests/__init__.py
- auctions/tests/model_tests.py
- auctions/views.py
- codesy/templates/base.html
- codesy/templates/includes/get_started.html
- codesy/templates/includes/stripe_form.html
- requirements-dev.txt
- static/css/codesy-home.css
This adds the user's next bid and/or claim call-to-action to the bid list as well as the widget. This code needs to get out of my head and terminal and in front of someone else ...
> fix #307: show claims & actions on bid-list

- codesy/settings.py
- codesy/templates/includes/get_started.html
- codesy/views.py
This is a fix to #357 but also moves the addon url and img details to settings.
> Add target

- codesy/settings.py
- codesy/templates/home.html
- codesy/templates/includes/faq.html
- codesy/templates/includes/get_started.html
- requirements.txt
This creates a CSP by installing django-csp.  Remember to run pip install.
The CSP is needed to allow github OAuth from inside the widget iframe.  It also is needed to add youtube video in an iframe on the home page!
> Create csp and add video

- codesy/templates/account/account_inactive.html
Changes:
-Explain the next step better
-add the #fixthebugs hashtag
> update inactive message

- codesy/templates/includes/faq.html
- codesy/templates/includes/terms.html
Fixes public facing misspellings of claimant (not claimaint).
> Spell check

- static/js/widget-app.js
Widget-app now checks the original bid offer to see if it is a new offer.
> add check for new offer and tell user

- codesy/templates/base.html
- codesy/templates/includes/faq.html
- codesy/templates/includes/how_it_works.html
These were a suggestion from our install testing in January.
> Home page fixes

- auctions/templates/addon/register_card.html
Used the id codesy-input to use the existing css for a quick fix.  Need to properly style ... one day.
> wrap message in codesy-input div fix #521

- codesy/base/admin.py
display stripe account statuses (customer & bank account)
> for #534: display, filter, and sort users by date

- codesy/base/models.py
- codesy/templates/includes/faq.html
- codesy/templates/includes/get_started.html
- codesy/templates/includes/how_it_works.html
1) This automatically activates on sign in with Github.
2) Changes the language and cleans up the pages users see when signing up.
> default to active users, clean up on board process

- codesy/base/admin.py
Starting with just 'username', 'first_name', 'last_name', 'email' fields.
> fix #534: admin action to export users to csv

- static/js/codesy-app.js
- static/js/widget-app.js
TODO: fix these colors up for a11y
> for #493: disable submit buttons while submitting

- payments/management/commands/calculate.py
- payments/tests/util_tests.py
- payments/utils.py
> Update calculations for transaction fees
