auctions/migrations/0005_auto_20150103_0221.py
auctions/models.py

I spot-checked by:
1. Open the chrome extension to an issue
2. Alter the bid form:
* remove the _method=PUT hidden input and 
* drop the bid ID from the action url
3. Submit the form

fix #69 - enforce unique bids per user per url

---

codesy/templates/home.html

Adds hidden installed element to the home page.  Change for codesy/chrome-extension#43 will hide install steps and reveal the new element when the extension is present.

for codesy/chrome-extension#43

---

codesy/settings.py

We use django-mailer's `send_mail` function explicitly, so we don't need to configure it as the global EMAIL_BACKEND.

fix #74 - remove EMAIL_BACKEND; add DEFAULT_FROM_EMAIL

---

auctions/migrations/0009_claim_evidence.py
auctions/models.py
auctions/serializers.py
auctions/templates/includes/claim_form.html
auctions/tests/serializer_tests.py

I need @jgmize or someone to tell me why https://127.0.0.1:8443/claim/confirmation?bid=11 is getting a 404 and not matching against [the `claim-by-bid` url pattern](https://github.com/codesy/codesy/blob/ca4a4cc82c65814917451003b350052e85877e81/auctions/urls.py#L15-L19)?

fix #161 - add evidence field to claims

---

auctions/templates/base_widget.html
codesy/settings.py
static/css/codesy-iframe.css
static/css/styles.css
tox.ini

Also removes click-jacking middleware protection. See https://github.com/codesy/codesy/issues/185 for replacement click-jacking protection.

separate css for iframe widget

---

auctions/admin.py
auctions/migrations/0010_vote.py
auctions/migrations/0011_auto_20160214_1622.py
auctions/models.py
auctions/serializers.py
auctions/tests/model_tests.py
auctions/tests/serializer_tests.py
auctions/tests/view_tests.py
auctions/urls.py
auctions/views.py
codesy/templates/claim_status.html

This adds the base Vote model and a VoteViewSet for default django-rest-framework API endpoints on the model.
Also includes some refactoring and test fixes for other issues that were easy to make here.

Add Vote model & VoteViewSet

---

auctions/models.py
auctions/tests/model_tests.py
auctions/tests/view_tests.py
auctions/views.py

Move the logic to automatically populate created and modified fields from DRF
viewset hooks into model signals.

fix #212, fix #214: move perform_create to models

---

auctions/models.py
auctions/tests/model_tests.py

Also, update tests to use object from the database, which requires
removing the tzinfo from them for comparison.

fix #246: use update() in datetime signal handler

---

requirements.txt

@jezdez fixed me up ... if you explicitly include `cffi` in `requirements.txt` the default heroku-buildpack-python detects it and bootstraps libffi for the build.
https://github.com/heroku/heroku-buildpack-python/blob/eab957c8c96acf1689ca98368a23940f2fe00e97/bin/steps/cryptography#L22-L35
This fixed the heroku build step. On to a `python manage.py migrate` problem next ...

add cffi to requirements.txt so heroku uses libffi

---

api/templates/claim_list.html
api/views.py
auctions/managers.py
auctions/models.py
auctions/tests/__init__.py
auctions/tests/managers_tests.py
auctions/tests/model_tests.py

Introduces a new `ClaimManager` class with a `voted_on_by_user` convenience method. Also refactors some `MarketTestCase` `setUp` into the `tests` module to make them more re-usable.

fix #277: add voted claims to claim list template

---

codesy/base/models.py

minor change to store user email in stripe email field instead of description.

save email in stripe customer email

---

codesy/settings.py

The addons are now live for everyone on Firefox and Opera stores.

new urls for firefox and opera

---

auctions/templates/addon/register_card.html
auctions/views.py
payments/templates/credit_card_page.html
payments/utils.py
static/js/widget-app.js

Tweaks to:
1) payment needs to use claimant's bank not offerer's
2) add charge id to offer when successfully paid
3) redirect user to cc form if cc token not saved
4) don't let widget submit a lowered offer

Payment offer testing

---

auctions/views.py

Opted for 404 instead of redirect.  This is easier and consistent with the post method.

fix #409: send to 404 if claim doesn't exist

---

payments/templates/bank_account_form.html
payments/templates/bank_account_page.html
payments/templates/credit_card_form.html
payments/templates/credit_card_page.html
static/js/stripe-app.js

Had to update the bank account template because stripe-app js is used for stripe forms.

fix #423: add success message when saving cc and bank info

---

auctions/templates/includes/payout.html
auctions/tests/view_tests.py
auctions/views.py
payments/templates/accept_terms.html
payments/templates/bank_account_form.html
payments/templates/verify_identity.html
payments/views.py
static/js/codesy-app.js

Added a "return_url" parameter to the bank url which is added by the claim form.  On a successful bank account setup, the codesy.app javascript redirects back to the claim form.
Test:
1) set up a new user or remove the Stripe bank account token from an existing user
2) approve a claim for the user
3) the claim status for the user should show the "register a bank account" message, click it.
4) the bank account form should load with "?return_url..." in the url
5) submit the form with and error like "asdf" in the routing number
6) you should be on the same form with an error message
7) change the routing number back to "110000000" and submit
8) you should return to the claime with the "Pay Me!" button

add return url to views and forms fix #488, fix #463

---

auctions/models.py
auctions/templates/bid_list.html
auctions/templates/claim_list.html
auctions/templates/includes/payout.html
auctions/views.py

Consolidated Credit and Fees instead of showing each one.
Steps To Reproduce:
1. user1 asks 100
2. user2 offers 70
3. user3 offers 30
4. user1 claims, is approved, and gets paid
Expected results:
On the claim page, user1 should only see a summary of all the fees and transactions involved in their payout.
Actual results:
On the claim page, user1 sees every individual transaction and its fees involved in their payout.

simplify payout details fix #484

---

codesy/base/middleware.py
codesy/settings.py

This should work, but now that I see its server-side implementation, the only thing that makes server-side better than detecting these requests paths on the client is future-proofing.
I.e., we can later update our `AUTH_CHANGING_PATHS` values on the server without pushing a new add-on update.

for #579: send http header when auth changes

---

codesy/base/middleware.py
codesy/settings.py
codesy/templates/base.html
codesy/urls.py
requirements.txt
static/css/codesy-home.css

Okay, this way it actually sends the `x-codes-auth-changed` header in the `200` response so that both Chrome and Firefox widgets can detect it.

fix #579: use allauth messages for header

---

payments/templates/bank_account_form.html

Adds these fields to the bank account form:
*first name 
*last name
*DOB fields
*account type
They are not required to add an account but are required when a payout is requested.  Might as well ask for them up front.

add fields required for payout to fix#610
